# Generated by Django 4.2.9 on 2026-03-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Rangrez', max_length=200)),
                ('tagline', models.CharField(default='Handcrafted Elegance from Rajasthan', max_length=500)),
                ('upi_id', models.CharField(blank=True, default='', max_length=200)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
