# Generated by Django 4.2.9 on 2026-03-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='store_name',
            field=models.CharField(default='Elegance', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Premium Fashion Collection', max_length=500),
        ),
    ]
