# Generated by Django 4.2.9 on 2026-03-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Main hero banner image', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
