# Generated by Django 4.2.9 on 2026-04-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_banner_image_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cashfree_app_id',
            field=models.CharField(blank=True, default='', help_text='Cashfree App ID', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cashfree_is_sandbox',
            field=models.BooleanField(default=True, help_text='Switch between Sandbox and Production modes'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cashfree_secret_key',
            field=models.CharField(blank=True, default='', help_text='Cashfree Secret Key', max_length=500),
        ),
    ]
