# Generated by Django 4.2.9 on 2026-04-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_cashfree_app_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='upi_id',
        ),
    ]
