# Generated by Django 4.2.9 on 2026-03-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_meesho_product',
            field=models.BooleanField(default=False, help_text='If true, product redirected to Meesho'),
        ),
        migrations.AddField(
            model_name='product',
            name='meesho_url',
            field=models.URLField(blank=True, help_text='Meesho product link', null=True),
        ),
    ]
