# Generated by Django 4.2.9 on 2026-03-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_meesho_product_product_meesho_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.PositiveIntegerField(default=10, help_text='Actual stock available'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags, e.g. Best Seller, New Arrival', max_length=200),
        ),
    ]
